# Generated by Django 5.0.6 on 2024-05-29 03:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jurusan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kodejurusan', models.CharField(max_length=50, verbose_name='Kode Program Studi')),
                ('namajurusan', models.CharField(max_length=150, verbose_name='Program')),
                ('jenjang', models.CharField(blank=True, max_length=150, null=True, verbose_name='Jenjang')),
            ],
        ),
        migrations.CreateModel(
            name='Mahasiswa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nim', models.CharField(max_length=50, verbose_name='Nim')),
                ('nama', models.CharField(max_length=150, verbose_name='Nama Lengkap')),
                ('jeniskelamin', models.CharField(choices=[('L', 'LAKI-LAKI'), ('P', 'PEREMPUAN')], max_length=50, verbose_name='Jenis Kelamin')),
                ('email', models.EmailField(blank=True, max_length=150, null=True, verbose_name='Email')),
                ('jurusan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perkuliahan.jurusan')),
            ],
        ),
    ]
