# Generated by Django 5.0.6 on 2024-05-29 04:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perkuliahan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matakuliah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kodemk', models.CharField(max_length=100, verbose_name='Kode Mata Kuliah')),
                ('namamk', models.CharField(max_length=150, verbose_name='Nama Mata Kuliah')),
                ('semester', models.CharField(max_length=50, verbose_name='Semester')),
                ('sks', models.IntegerField(verbose_name='SKS')),
                ('jurusan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perkuliahan.jurusan')),
            ],
        ),
    ]
